name: CI

on:
  push:
    branches:
    - entin/gh-actions

jobs:
  xcode-build:
    name: Xcode Build
    runs-on: macOS-latest
    strategy:
      matrix:
        platform: ['iOS_13'] #'iOS_12', 'iOS_11']
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Bundle Install
        run: bundle install --gemfile=Example/Gemfile
      - name: Pod Install
        run: bundle exec --gemfile=Example/Gemfile pod install --project-directory=Example
      - name: Build and Test
        run: Scripts/build.swift xcode ${{ matrix.platform }} # `which xcpretty`
        # env:
        #   platform: $
      - name: Upload Results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Test Results
          path: .build/derivedData/**/Logs/Test/*.xcresult
  pod-lint:
    name: Pod Lint
    runs-on: macOS-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Bundle Install
        run: bundle install --gemfile=Example/Gemfile
      - name: Pod Install
        run: bundle exec --gemfile=Example/Gemfile pod install --project-directory=Example
      - name: Lint Podspec
        run: bundle exec --gemfile=Example/Gemfile pod lib lint --verbose --fail-fast
